apiVersion: v1
kind: Service
metadata:
  labels:
    app: odoo
  name: odoo
spec:
  type: LoadBalancer
  ports:
    - port: 8069
      targetPort: 8069
      protocol: TCP
  selector:
    app: odoo-shop
